default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development_journals.sqlite3

test:
  <<: *default
  database: db/test_journals.sqlite3

production:
  <<: *default
  database: db/production_journals.sqlite3
